
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Nautolan_Invaders(

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


wire CLK_25;
assign VGA_BLANK_N = 1'b1;
assign VGA_CLK = CLK_25;

//=======================================================
//  Structural coding
//=======================================================

CLK_divider_25MHz(.CLK(CLOCK_50),.CLK_divided(CLK_25));

main(.CLK(CLK_25),.RESET(SW[0]),.Weapon_switch(KEY[3]),.Fire(KEY[2]),.Rotate_CW(KEY[0]),.Rotate_CCW(KEY[1]),.hsync(VGA_HS),.vsync(VGA_VS),.red(VGA_R),.green(VGA_G),.blue(VGA_B),.deneme1(LEDR[0]),.deneme2(LEDR[1]));


endmodule
